codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 75%
        threshold: 10%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "node_modules/**/*"
  - "test/**/*"
  - "scripts/**/*"
  - "artifacts/**/*"
  - "cache/**/*"
  - "typechain/**/*"
  - "typechain-types/**/*"
  - "coverage/**/*"
  - "**/*.config.js"
  - "**/*.config.ts"
